#!/bin/bash

# Config home
XDG_CONFIG_HOME="$HOME/.config"

mkdir -p "$XDG_CONFIG_HOME"

# symlinks
ln -s "$HOME/dotfiles/nvim" "$XDG_CONFIG_HOME/nvim"

# Packages to brew install
packages=("lazygit" "fd" "fzf" "ripgrep" "gcc")

for package in "${packages[@]}"; do
  echo "Installing $package..."
  /home/linuxbrew/.linuxbrew/bin/brew install "$package"
done

# Final message
echo "Setup completed"
